### ISSUE TITLE
Invalid Signature 759f5facc60f4b021d18b806ce79756a924321ed. String to sign - 'public_id={\"0\"=>\"60\", \"1\"=>\"

### ISSUE THREAD

**Issue by chikeozulumba** [jrm2k6/cloudder#54]
Hi there,

I keep getting this issue when trying to upload.
All configurations are set and cross-checked.

this is a sample of my code
`public function test (Request $request)
    {
        if ($request->hasFile('file')) {
            \Cloudder::upload($request->file('file'), ["timeout" => 60, "folder" => "folder"]);
            $c=\Cloudder::getResult();
            if($c){
                return $c['url'];
                return back()
                    ->with('success','You have successfully upload images.')
                    ->with('image',$c['url']);
            }
        } else {
            return 'false';
        }
    }`

**Comment by jrm2k6** [comment]
Hi, sorry for the delay.
Did you find a solution for your issue?

**Comment by mbengchan** [comment]
@codeNigga it's a syntax error you are having. i had the same issue i solved it by doing this:

`\Cloudder::upload($request->file('file'), null, ["timeout" => 60, "folder" => "folder"]);`

since the upload method definition is like this

`upload($source, $publicId = null, $uploadOptions = array(), $tags = array())`

Hope that helps

**Comment by jrm2k6** [comment]
@Shadomax Thanks, yes that looks likely to be the issue.
